import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Header from '../components/Header/Header';
import StoreProvider from './StoreProvider';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'О-комплекс',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<StoreProvider>
			<html lang='ru'>
				<body className={inter.className}>
					<div className='page'>
						<Header />
						{children}
					</div>
				</body>
			</html>
		</StoreProvider>
	);
}
